doctrine:
    dbal:
        dbname: '%env(DATABASE_DBNAME)%'
        host: '%env(DATABASE_HOST)%'
        port: '%env(DATABASE_PORT)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        driver: '%env(DATABASE_DRIVER)%'
        types:
            lead_uuid: Cal\Leads\Infrastructure\Persistence\Doctrine\ValueObjectLeadUuidType
            lead_name: Cal\Leads\Infrastructure\Persistence\Doctrine\ValueObjectLeadNameType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Leads:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Leads/Infrastructure/Persistence/Doctrine'
                prefix: 'Cal\Leads\Domain'
                alias: Cal\Leads\Domain
