parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../app/'
        exclude:
            - '../app/DependencyInjection/'
            - '../app/Entity/'
            - '../app/Kernel.php'
            - '../app/Tests/'

    App\Controller\:
        resource: '../app/Controller/'
        tags: ['controller.service_arguments']

    Cal\:
        resource: '../src/'
        exclude:
            - '../src/Shared/Domain/helpers.php'

    Cal\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }