name: PHP Composer

on:
  push:
    branches: [ master, feature/*, release/* ]
  pull_request:
    branches: [ master, release/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Check code style
      run: vendor/bin/php-cs-fixer fix --dry-run --diff --config .php_cs.dist

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse -c phpstan.neon

    - name: Unit testing
      run: vendor/bin/phpunit --testsuite Unit

    - name: Integration testing
      run: vendor/bin/phpunit --testsuite Integration
      env:
        DATABASE_HOST: 127.0.0.1
        DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
        DATABASE_USER: root
        DATABASE_PASSWORD: password

    - name: Feature testing
      run: vendor/bin/behat
      env:
        DATABASE_HOST: 127.0.0.1
        DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
        DATABASE_USER: root
        DATABASE_PASSWORD: password