name: PHP Composer

on:
  push:
    branches: [ master, feature/*, release/* ]
  pull_request:
    branches: [ master, release/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Check code style
      run: vendor/bin/php-cs-fixer fix --dry-run --diff --config .php_cs.dist

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse -c phpstan.neon

    - name: Unit testing
      run: vendor/bin/phpunit --testsuite Unit

    - name: Integration testing
      run: vendor/bin/phpunit --testsuite Integration

    - name: Feature test
      run: vendor/bin/behat